# Generated by Django 4.0.4 on 2022-04-18 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('resumo', models.CharField(max_length=300)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('citacao', models.CharField(default='SOME STRING', max_length=1000)),
                ('paragrafo', models.TextField(default='SOME STRING')),
                ('publicar', models.BooleanField(default=True)),
                ('foto_postagem', models.ImageField(blank=b'I01\n', upload_to='fotos/%d/%m/%Y/')),
            ],
        ),
    ]
