# Generated by Django 4.0.4 on 2022-04-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0001_initial'),
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Pessoas.pessoas_cad'),
            preserve_default=False,
        ),
    ]
