# Generated by Django 4.0.4 on 2022-04-20 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webapp', '0002_postagem_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
